-- Baseline schema for HelloFamily.
--
-- ⚠️ ALREADY APPLIED ON THE REMOTE PROJECT — DO NOT RUN THIS AGAINST THE
-- DATABASE. This file was reconstructed on 2026-08-12 via read-only SQL
-- introspection (information_schema / pg_catalog / pg_policies, through
-- `supabase db query --linked`) because `supabase db pull` was unavailable
-- (it requires a local Docker shadow database, and Docker isn't installed
-- on this machine). It exists purely so this repo's migration history
-- reflects what's actually on the remote project. See
-- docs/database-schema.md for a human-readable explanation, and CLAUDE.md
-- for how it was produced and its caveats.
--
-- This represents the schema as it existed BEFORE
-- 20260812050147_create_invite_functions.sql was applied (that migration
-- is unchanged and still applies its delta on top of this baseline:
-- invites.contact, idx_invites_created_by, invites_select_own, and the
-- create_invite/redeem_invite functions).
--
-- The one exception is the trigger on `auth.users` (a managed schema),
-- which is captured separately in
-- 20260806000001_auth_schema_new_user_trigger.sql per this project's rule
-- of keeping auth-schema changes clearly isolated.
--
-- If the schema needs to change going forward, write a NEW migration —
-- do not edit this file retroactively.

-- ============================================================
-- Enums
-- ============================================================

create type public.user_role as enum ('adult_child', 'older_adult');
create type public.connection_status as enum ('active', 'revoked');
create type public.invite_status as enum ('pending', 'accepted', 'expired', 'revoked');
create type public.feeling_answer as enum ('good', 'okay', 'not_good');
create type public.wellness_answer as enum ('yes', 'mostly', 'no');
create type public.checkin_status as enum ('completed', 'concern', 'missed');

-- ============================================================
-- Shared helper functions
-- ============================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- private schema: SECURITY DEFINER helpers used inside RLS policies, so a
-- policy checking "is this user connected to that one" doesn't need the
-- querying role to have direct SELECT on family_connections itself.
create schema if not exists private;

create or replace function private.are_connected(first_user uuid, second_user uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.family_connections fc
    where fc.status = 'active'
      and (
        (fc.adult_child_id = first_user and fc.older_adult_id = second_user)
        or
        (fc.adult_child_id = second_user and fc.older_adult_id = first_user)
      )
  );
$$;

create or replace function private.is_connected_adult_child(possible_adult_child uuid, older_adult uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.family_connections fc
    where fc.status = 'active'
      and fc.adult_child_id = possible_adult_child
      and fc.older_adult_id = older_adult
  );
$$;

-- handle_new_user is defined here (it's a public-schema function); the
-- trigger that attaches it to auth.users lives in the separate
-- auth-schema migration file.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_role public.user_role;
  selected_timezone text;
begin
  selected_role :=
    case
      when new.raw_user_meta_data ->> 'role'
        in ('adult_child', 'older_adult')
      then (new.raw_user_meta_data ->> 'role')::public.user_role
      else null
    end;

  selected_timezone :=
    coalesce(
      nullif(new.raw_user_meta_data ->> 'timezone', ''),
      'America/Chicago'
    );

  insert into public.profiles (id, full_name, role, timezone)
  values (
    new.id,
    nullif(new.raw_user_meta_data ->> 'full_name', ''),
    selected_role,
    selected_timezone
  );

  insert into public.notification_preferences (user_id, timezone)
  values (new.id, selected_timezone);

  return new;
end;
$$;

-- ============================================================
-- profiles
-- ============================================================

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text,
  role public.user_role,
  timezone text not null default 'America/Chicago',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_full_name_length check (
    full_name is null or (char_length(full_name) >= 1 and char_length(full_name) <= 100)
  )
);

alter table public.profiles enable row level security;

create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

grant select, insert, update on public.profiles to authenticated;

create policy "Users can read their own or connected profiles"
  on public.profiles for select
  to authenticated
  using ((select auth.uid()) = id or private.are_connected((select auth.uid()), id));

create policy "Users can insert their own profile"
  on public.profiles for insert
  to authenticated
  with check ((select auth.uid()) = id);

create policy "Users can update their own profile"
  on public.profiles for update
  to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

-- ============================================================
-- family_connections
-- ============================================================

create table public.family_connections (
  id uuid primary key default gen_random_uuid(),
  adult_child_id uuid not null references public.profiles (id) on delete cascade,
  older_adult_id uuid not null references public.profiles (id) on delete cascade,
  status public.connection_status not null default 'active',
  connected_at timestamptz not null default now(),
  revoked_at timestamptz,
  constraint different_family_members check (adult_child_id <> older_adult_id),
  constraint unique_family_connection unique (adult_child_id, older_adult_id)
);

create index family_connections_adult_child_idx on public.family_connections (adult_child_id);
create index family_connections_older_adult_idx on public.family_connections (older_adult_id);

alter table public.family_connections enable row level security;

grant select on public.family_connections to authenticated;

create policy "Connected users can read their connection"
  on public.family_connections for select
  to authenticated
  using ((select auth.uid()) = adult_child_id or (select auth.uid()) = older_adult_id);

-- No insert/update/delete policy or grant for `authenticated`: connections
-- are only ever created via the redeem_invite() SECURITY DEFINER function
-- (see 20260812050147_create_invite_functions.sql).

-- ============================================================
-- invites
-- ============================================================

-- NOTE: `invites.contact`, the `idx_invites_created_by` index, and the
-- `invites_select_own` policy are added later by
-- 20260812050147_create_invite_functions.sql — not part of this baseline.
create table public.invites (
  id uuid primary key default gen_random_uuid(),
  created_by uuid not null references public.profiles (id) on delete cascade,
  token_hash text not null unique,
  status public.invite_status not null default 'pending',
  expires_at timestamptz not null,
  used_by uuid references public.profiles (id) on delete set null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index invites_created_by_idx on public.invites (created_by);

alter table public.invites enable row level security;

-- Deliberately no grants to `authenticated` here: at baseline, the mobile
-- client had zero direct privileges on this table (see docs/prd's privacy
-- rules) — everything went through create_invite()/redeem_invite().

-- ============================================================
-- check_ins
-- ============================================================

create table public.check_ins (
  id uuid primary key default gen_random_uuid(),
  older_adult_id uuid not null references public.profiles (id) on delete cascade,
  check_in_date date not null,
  feeling public.feeling_answer not null,
  physically_okay public.wellness_answer not null,
  normal_activities public.wellness_answer not null,
  concern_detected boolean generated always as (
    feeling = 'not_good'::public.feeling_answer
    or physically_okay = 'no'::public.wellness_answer
    or normal_activities = 'no'::public.wellness_answer
  ) stored,
  submitted_at timestamptz not null default now(),
  constraint one_check_in_per_day unique (older_adult_id, check_in_date)
);

create index check_ins_older_adult_date_idx on public.check_ins (older_adult_id, check_in_date desc);

alter table public.check_ins enable row level security;

grant select, insert on public.check_ins to authenticated;

create policy "Older adults can read their own answers"
  on public.check_ins for select
  to authenticated
  using ((select auth.uid()) = older_adult_id);

create policy "Older adults can submit their own check-ins"
  on public.check_ins for insert
  to authenticated
  with check ((select auth.uid()) = older_adult_id);

-- No update/delete policy or grant: check-in history is immutable from
-- the client by design.

-- ============================================================
-- daily_statuses
-- ============================================================

create table public.daily_statuses (
  id uuid primary key default gen_random_uuid(),
  older_adult_id uuid not null references public.profiles (id) on delete cascade,
  status_date date not null,
  status public.checkin_status not null,
  completed_at timestamptz,
  check_in_id uuid unique references public.check_ins (id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint one_status_per_day unique (older_adult_id, status_date),
  constraint valid_status_details check (
    (status in ('completed', 'concern') and check_in_id is not null and completed_at is not null)
    or
    (status = 'missed' and check_in_id is null and completed_at is null)
  )
);

create index daily_statuses_older_adult_date_idx on public.daily_statuses (older_adult_id, status_date desc);

alter table public.daily_statuses enable row level security;

grant select on public.daily_statuses to authenticated;

create policy "Older adults and connected adult children can read statuses"
  on public.daily_statuses for select
  to authenticated
  using (
    (select auth.uid()) = older_adult_id
    or private.is_connected_adult_child((select auth.uid()), older_adult_id)
  );

-- No insert/update/delete policy or grant: rows are created only by the
-- create_status_from_check_in() trigger (or, in future, a trusted
-- scheduled backend process for "missed").

-- ============================================================
-- check_ins -> daily_statuses trigger
-- ============================================================

create or replace function public.create_status_from_check_in()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.daily_statuses (
    older_adult_id, status_date, status, completed_at, check_in_id
  )
  values (
    new.older_adult_id,
    new.check_in_date,
    case
      when new.concern_detected then 'concern'::public.checkin_status
      else 'completed'::public.checkin_status
    end,
    new.submitted_at,
    new.id
  );
  return new;
end;
$$;

create trigger on_check_in_created
  after insert on public.check_ins
  for each row execute function public.create_status_from_check_in();

-- ============================================================
-- notification_preferences
-- ============================================================

create table public.notification_preferences (
  user_id uuid primary key references public.profiles (id) on delete cascade,
  timezone text not null default 'America/Chicago',
  daily_reminder_time time not null default '18:00:00',
  missed_check_in_cutoff time not null default '21:00:00',
  daily_reminder_enabled boolean not null default true,
  completed_alert_enabled boolean not null default true,
  concern_alert_enabled boolean not null default true,
  missed_alert_enabled boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.notification_preferences enable row level security;

create trigger notification_preferences_set_updated_at
  before update on public.notification_preferences
  for each row execute function public.set_updated_at();

grant select, insert, update on public.notification_preferences to authenticated;

create policy "Users can read their notification preferences"
  on public.notification_preferences for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can insert their notification preferences"
  on public.notification_preferences for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Users can update their notification preferences"
  on public.notification_preferences for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

-- ============================================================
-- push_tokens
-- ============================================================

create table public.push_tokens (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  expo_push_token text not null unique,
  platform text not null default 'ios',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint valid_push_platform check (platform in ('ios', 'android'))
);

create index push_tokens_user_idx on public.push_tokens (user_id);

alter table public.push_tokens enable row level security;

create trigger push_tokens_set_updated_at
  before update on public.push_tokens
  for each row execute function public.set_updated_at();

grant select, insert, update, delete on public.push_tokens to authenticated;

create policy "Users can read their own push tokens"
  on public.push_tokens for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can add their own push tokens"
  on public.push_tokens for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Users can update their own push tokens"
  on public.push_tokens for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users can delete their own push tokens"
  on public.push_tokens for delete
  to authenticated
  using ((select auth.uid()) = user_id);
